import Head from "next/head";
import "../styles/Home.module.scss";
import Description from "../components/Description";
import Project from "../components/Project";
import Document from "../components/Document";
import Footer from "../components/Footer";
import Slider from "../components/Slider";
import Navbar from "../components/Navbar";
const Airtable = require("airtable");
const { AIRTABLE_API_KEY, AIRTABLE_BASE_ID } = process.env;

export default function Home({ profil, project, document, slider, logo }) {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider slider={slider} profil={profil} />
      <Navbar logo={logo} />
      <Description profil={profil} />
      <Project project={project} />
      <Document document={document} />
      <Footer siret={profil.siret} />
    </>
  );
}

export const getStaticProps = async () => {
  const Api = async (data, filter) => {
    const base = new Airtable({ apiKey: AIRTABLE_API_KEY }).base(
      AIRTABLE_BASE_ID
    );

    const response = await base(data)
      .select(filter)
      .firstPage()
      .catch((e) => {
        console.log(e);
      });

    const records = await response.map((record) => {
      return {
        id: record.id,
        ...record.fields,
      };
    });
    return records;
  };

  const profil = await Api("Profil", { filterByFormula: `id = 1` });
  const project = await Api("Project", {});
  const document = await Api("Document", {});
  const slider = await Api("Carousel", {});
  return {
    props: {
      profil: profil[0],
      project,
      document,
      slider,
      logo: profil[0].logo[0],
    },
    revalidate: 60,
  };
};
