import Head from "next/head";
import { Inter } from "@next/font/google";
import "../styles/Home.module.scss";
import Description from "../components/Description";
import axios from "axios";
import Project from "../components/Project";
import Document from "../components/Document";
import Footer from "../components/Footer";
import Slider from "../components/Slider";
import Navbar from "../components/Navbar";
const Airtable = require("airtable");
const { AIRTABLE_API_KEY, AIRTABLE_BASE_ID } = process.env;

const inter = Inter({ subsets: ["latin"] });

export default function Home({ profil, project, document, slider }) {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider slider={slider} profil={profil} />
      <Navbar />
      <Description profil={profil} />
      <Project project={project} />
      <Document document={document} />
      <Footer siret={profil.siret} />
    </>
  );
}

export const getStaticProps = async () => {
  const myProfil = new Airtable({ apiKey: AIRTABLE_API_KEY }).base(
    AIRTABLE_BASE_ID
  );

  const response = await myProfil("Profil")
    .select({ filterByFormula: `id = 1` })
    .firstPage()
    .catch((e) => {
      console.log(e);
    });

  const profil = response.map((record) => {
    return {
      id: record.id,
      ...record.fields,
    };
  });

  const projects = new Airtable({ apiKey: AIRTABLE_API_KEY }).base(
    AIRTABLE_BASE_ID
  );

  const secondResponse = await projects("Project")
    .select({})
    .firstPage()
    .catch((e) => {
      console.log(e);
    });

  const project = secondResponse.map((record) => {
    return {
      id: record.id,
      ...record.fields,
    };
  });

  const documents = new Airtable({ apiKey: AIRTABLE_API_KEY }).base(
    AIRTABLE_BASE_ID
  );

  const ThirdResponse = await documents("Document")
    .select({})
    .firstPage()
    .catch((e) => {
      console.log(e);
    });

  const document = ThirdResponse.map((record) => {
    return {
      id: record.id,
      ...record.fields,
    };
  });

  const secondBase = new Airtable({ apiKey: AIRTABLE_API_KEY }).base(
    AIRTABLE_BASE_ID
  );

  const fourthResponse = await secondBase("Carousel")
    .select({})
    .firstPage()
    .catch((e) => {
      console.log(e);
    });

  const slider = fourthResponse.map((record) => {
    return {
      id: record.id,
      ...record.fields,
    };
  });

  return {
    props: {
      profil: profil[0],
      project,
      document,
      slider,
    },
  };
};
